# Generated by Django 4.2.1 on 2023-05-23 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_model',
            field=models.CharField(max_length=21, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
